#!/bin/bash
# Aurelio Jargas, http://aurelio.net/moneylog/
#
# Script to join all the MoneyLog pieces in one singe HTML file, generating
# the MoneyLog Browser version, who uses localStorage instead of text files.
#
# Usage:
#	gen-browser [--lang XX]
#
# Examples:
#	gen-browser                   # Portuguese browser version
#	gen-browser --lang en         # English browser version
#
# Note:
#	The results are Windows-style line break: CR+LF


cd $(dirname "$0")

lang="pt"           # pt, en, es, ca. Use --lang to change it.

# Option --lang
if test "$1" = '--lang'
then
	lang=$2
	shift
	shift
fi

# Files
html_path="../moneylog.html"
txt_path="../sample/data-$lang.txt"

# Set $commit_id to the latest Git commit hash
source set-commit-id.sh

# Patterns:
# <link rel="stylesheet" type="text/css" href="moneylog.css">
# <script type="text/javascript" src="moneylog.js"></script>

insert_css='
/^<link .*href="moneylog.css"/ {
	a \
<style type="text/css">
	r ../moneylog.css
	a \
</style>\
<style type="text/css">
	r ../css/browser.css
	a \
</style>
	d
}

/^<link .*href="css\/mobile.css"/ {
	a \
<style type="text/css">
	r ../css/mobile.css
	a \
</style>
	d
}

/^<link .*href="css\/print.css"/ {
	a \
<style type="text/css" media="print">
	r ../css/print.css
	a \
</style>
	d
}
'
insert_js='
/^<script .*src="moneylog.js"/ {
	a \
<script type="text/javascript">
	r ../moneylog.js
	a \
</script>
	d
}
'
insert_txt="
/^<pre/ r $txt_path
"

echo "$insert_css $insert_js $insert_txt" > sed_script

# Do it
control_m=$(printf '\r')

sed -f sed_script "$html_path" |
	# Set language
	sed "/^var lang = 'pt';/ s/pt/$lang/" |
	# Set commit id
	sed "/^var appCommit = '';/ s/'/'$commit_id/" |
	# clean up
	sed '
		# Remove config.js call
		/^<script .* src="config.js"><\/script>/ d

		# Turn ON localStorage
		/^var appMode = .txt.;/ s/txt/localStorage/
	' |
	# unix2dos: Remove any CR, then add one per line, becoming CR+LF
	sed "s/$control_m*$/$control_m/"

# Clean up
rm -f sed_script
