#!/bin/bash
# Aurelio Jargas, http://aurelio.net/moneylog/
#
# Script to join all the Moneylog pieces in one singe HTML file, generating
# the Moneylog Online version, who uses localStorage instead of text files.
#
# Usage:
#	gen-online [--lang XX]
#
# Examples:
#	gen-online                   # Portuguese online version
#	gen-online --lang en         # English online version


lang="pt"           # pt, en, es, ca. Use --lang to change it.

# Files
html_path="../moneylog.html"
txt_path="../moneylog.txt"

# Option --lang
if test "$1" = '--lang'
then
	lang=$2
	shift
	shift
fi

# Language adjustments
if test "$lang" != 'pt'
then
	txt_path="../moneylog-$lang.txt"
fi

# Patterns:
# <link rel="stylesheet" type="text/css" href="moneylog.css">
# <script type="text/javascript" src="moneylog.js"></script>

insert_css='
/^<link .*href="moneylog.css"/ {
	a \
<style type="text/css">
	r ../moneylog.css
	a \
</style>
	d
}
'
insert_js='
/^<script .*src="moneylog.js"/ {
	a \
<script type="text/javascript">
	r ../moneylog.js
	a \
</script>
	d
}
'
insert_txt="
$ r $txt_path
"

echo "$insert_css $insert_js $insert_txt" > sed_script

# Do it
control_m=$(printf '\r');

sed -f sed_script "$html_path" |
	# dos2unix: remove CR
	sed "s/$control_m*$//" |
	# Set language
	sed "/^var lang = 'pt';/ s/pt/$lang/" |
	# clean up
	sed '
		# Remove config.js call
		/^<script .* src="config.js"><\/script>/ d

		# Turn ON localStorage
		/^var useLocalStorage = false;/ s/false/true/
		/^var oneFile = true;/ s/true/false/

		# Remove ml v3 theme
		/^\/\* MoneyLog v3 Theme/, /^\*\/$/ d
	
		# # Remove all comment blocks (DISABLED)
		# /^<!--$/, /^-->$/ d
		# /^\/\*\*\**$/, /^\*\*\*\**\/$/ d
	'

# Close the opened tags, since user won't edit this file
echo "</pre></body></html>"

# Clean up
rm -f sed_script
