#!/bin/bash
# Aurelio Jargas, http://aurelio.net/moneylog/
#
# Generates the commented config.js sample, with Beta specific sections.
#
# Usage:
#	gen-beta-config [--lang XX]
#
# Examples:
#	gen-beta-config                  # Portuguese version
#	gen-beta-config --lang en        # English version


cd $(dirname "$0")

lang="pt"           # pt, en, es, ca. Use --lang to change it.

# Option --lang
if test "$1" = '--lang'
then
	lang=$2
	shift
	shift
fi

file_path="../sample/config-$lang.js"

if test -f "$file_path"
then
	sed '
		# Remove Dropbox-specific data
		/^\/\/<Dropbox>/, /^\/\/<\/Dropbox>/ d

		# Remove marker lines
		/^\/\/<Beta>/ d
		/^\/\/<\/Beta>/ d
	
	' "$file_path"
else
	echo "Sorry, file not found: $file_path"
fi
