#!/bin/bash
# Aurelio Jargas, http://aurelio.net/moneylog/
#
# Generates the commented config.js sample, with Dropbox specific sections.
#
# Usage:
#	gen-dropbox-config [--lang XX]
#
# Examples:
#	gen-dropbox-config                   # Portuguese version
#	gen-dropbox-config --lang en         # English version


cd $(dirname "$0")

lang="pt"           # pt, en, es, ca. Use --lang to change it.

# Option --lang
if test "$1" = '--lang'
then
	lang=$2
	shift
	shift
fi

file_path="../extra/config-$lang.js"

if test -f "$file_path"
then
	sed '
		# Remove SVN-specific data
		/^\/\/<SVN>/, /^\/\/<\/SVN>/ d

		# Remove marker lines
		/^\/\/<Dropbox>/ d
		/^\/\/<\/Dropbox>/ d
	
	' "$file_path"
else
	echo "Sorry, file not found: $file_path"
fi
