#!/bin/bash
# Aurelio Jargas, http://aurelio.net/moneylog/
#
# Script to join all the MoneyLog pieces in one singe HTML file, generating
# the MoneyLog Cloud (Dropbox) version.
#
# Usage:
#	gen-cloud [--lang XX]
#
# Examples:
#	gen-cloud                   # Portuguese cloud version
#	gen-cloud --lang en         # English cloud version
#
# Note:
#	The results are Unix-style line break: LF


cd $(dirname "$0")

lang="pt"           # pt, en, es, ca. Use --lang to change it.

# Files
html_path="../moneylog.html"
txt_path="../moneylog.txt"

# Option --lang
if test "$1" = '--lang'
then
	lang=$2
	shift
	shift
fi

# Language adjustments
if test "$lang" != 'pt'
then
	txt_path="../moneylog-$lang.txt"
fi

# Patterns:
# <link rel="stylesheet" type="text/css" href="moneylog.css">
# <script type="text/javascript" src="moneylog.js"></script>

insert_css='
/^<link .*href="moneylog.css"/ {
	a \
<style type="text/css">
	r ../moneylog.css
	a \
</style>\
<style type="text/css">
	r ../extra/cloud.css
	a \
</style>
	d
}

/^<link .*href="extra\/mobile.css"/ {
	a \
<style type="text/css">
	r ../extra/mobile.css
	a \
</style>
	d
}

/^<link .*href="extra\/print.css"/ {
	a \
<style type="text/css" media="print">
	r ../extra/print.css
	a \
</style>
	d
}
'
insert_js='
/^<script .*src="moneylog.js"/ {
	a \
<script type="text/javascript">
	r ../moneylog.js
	a \
</script>\
\
<script src="js/jquery-1.7.1.min.js" type="text/javascript" ></script>\
<script src="/js/moneylog_dropbox.js" type="text/javascript"></script>\
{{ user_config }}
	d
}
'
insert_txt="
/^<pre/ r $txt_path
"
insert_meta='
/^<link rel="shortcut icon"/ a \
<link rel="apple-touch-icon" href="images/ios_icon.png" />\
<link rel="apple-touch-startup-image" href="images/ios_splash.png" />
'
insert_analytics='
/^<\/head>/ {
	r gen-cloud-analytics.html
	a \
</head>
	d
}
'

echo "$insert_css $insert_js $insert_txt $insert_meta $insert_analytics" > sed_script

# Do it
control_m=$(printf '\r');

sed -f sed_script "$html_path" |
	# Set language
	sed "/^var lang = 'pt';/ s/pt/$lang/" |
	# clean up
	sed '
		# Remove config.js call
		/^<script .* src="config.js"><\/script>/ d

		# Turn ON Dropbox support
		/^var appMode = .txt.;/ s/txt/dropbox/
	' |
	# dos2unix: remove CR
	sed "s/$control_m*$//"

# Clean up
rm -f sed_script
