#!/bin/bash
# Aurelio Jargas, https://aurelio.net/moneylog/
#
# Generates the commented config.js sample, with Dropbox specific sections.
#
# Usage:
#	gen-cloud-config [--lang XX]
#
# Examples:
#	gen-cloud-config                   # Portuguese version
#	gen-cloud-config --lang en         # English version


cd $(dirname "$0")

lang="pt"           # pt, en, es, ca. Use --lang to change it.

# Option --lang
if test "$1" = '--lang'
then
	lang=$2
	shift
	shift
fi

file_path="../sample/config-$lang.js"

if test -f "$file_path"
then
	sed '
		# Remove Beta-specific data
		/^\/\/ <Beta>/, /^\/\/ <\/Beta>/ d

		# Remove marker lines
		/^\/\/ <Dropbox>/ d
		/^\/\/ <\/Dropbox>/ d
	
	' "$file_path"
else
	echo "Sorry, file not found: $file_path"
fi
